workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.salarytopup.app"
        APP_STORE_APPLE_ID: "ADD_YOUR_APP_ID_HERE"
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.salarytopup.app

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Pod install
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Flutter build iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
